python shape.py 1.png > 1.txt
python shape.py 2.png > 2.txt
python shape.py 3.png > 3.txt
python shape.py 4.png > 4.txt
python shape.py 5.png > 5.txt
python shape.py 6.png > 6.txt
python shape.py 7.png > 7.txt
python shape.py 8.png > 8.txt
python shape.py 9.png > 9.txt
python shape.py 10.png > 10.txt
python shape.py 11.png > 11.txt
python shape.py 12.png > 12.txt
python shape.py 13.png > 13.txt
python shape.py 14.png > 14.txt
python shape.py 15.png > 15.txt
python shape.py 16.png > 16.txt
python shape.py 17.png > 17.txt
python shape.py 18.png > 18.txt
